# Generated by Django 4.2.20 on 2025-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('company_location', models.CharField(max_length=255)),
            ],
        ),
    ]
