# Generated by Django 4.2.20 on 2025-03-27 10:09

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_location', models.CharField(max_length=255)),
                ('info_id', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='pdfs/', validators=[files.models.validate_pdf])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
