# Generated by Django 4.2.20 on 2025-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_pdfupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='info_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
