# Generated by Django 4.2.20 on 2025-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_pdfupload_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='image',
            field=models.ImageField(default='login-form/images/pdf_pics.png', upload_to='images/'),
        ),
    ]
