# Generated by Django 4.2.20 on 2025-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_pdfupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='company_location',
            field=models.CharField(max_length=50),
        ),
    ]
