# Generated by Django 4.2.20 on 2025-04-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_pdfupload_company_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
