# Generated by Django 4.2.20 on 2025-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
