# Generated by Django 4.2.20 on 2025-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_gallery_description_remove_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_file',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
