# Generated by Django 4.2.20 on 2025-04-12 21:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_gallery_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='hymns/images/')),
                ('lyrics', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
