# Generated by Django 4.2.20 on 2025-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_hymn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
