# Generated by Django 4.2.20 on 2025-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_hymn_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hymn',
            name='hymn_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('the_lords_day', "The Lord's Day"), ('praises', 'Praises'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('closing_opening_year', 'Closing and Opening of the Year'), ('warning_petition_gospel_call', 'Warning, Petition and Gospel Call'), ('lent_repentance', 'Lent and Repentance'), ('palm_sunday', 'Palm Sunday'), ('suffering_death', 'Suffering and Death'), ('resurrection', 'Resurrection'), ('lords_day_after_resurrection', "Lord's Day after Resurrection"), ('ascension', 'Ascension'), ('holy_ghost', 'Holy Ghost'), ('pentecostal_revival', 'Pentecostal Revival'), ('missionary', 'Missionary'), ('word_of_god', 'The Word of God'), ('baptism', 'Baptism'), ('holy_communion', 'Holy Communion'), ('holy_matrimony', 'Holy Matrimony'), ('children_youth', 'Children and Youth'), ('prayer', 'Prayer'), ('divine_healing', 'Divine Healing'), ('faith', 'Faith'), ('unity_peace', 'Unity and Peace'), ('time_old_age', 'Time of Old Age'), ('harvest_anniversaries', 'Harvest and Anniversaries'), ('love', 'Love'), ('guidance_protection', 'Guidance and Protection'), ('labour_service', 'Labour and Service'), ('trials_victories', 'Trials and Victories'), ('encouragement', 'Encouragement'), ('building_dedication', 'Building and Dedication'), ('servants_for_god', 'Servants for God'), ('farewell', 'Farewell'), ('church_heaven_earth', 'The Church in Heaven and Earth'), ('various_hymns', 'Various Hymns')], default='morning', max_length=50),
        ),
    ]
