# Generated by Django 4.2.20 on 2025-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_frenchhymn'),
    ]

    operations = [
        migrations.CreateModel(
            name='HausaHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hymn_type', models.CharField(choices=[('morning', 'Safe'), ('evening', 'Yamma'), ('the_lords_day', 'Ranar Ubangiji'), ('praises', 'Yabo'), ('advent', 'Zuƙowa'), ('christmas', 'Kirsimeti'), ('closing_opening_year', 'Rufe da Buɗe Sabuwar Shekara'), ('warning_petition_gospel_call', 'Gargaɗi, Roƙo da Kiran Bishara'), ('lent_repentance', 'Azumi da Tuba'), ('palm_sunday', 'Lahadin Ganye'), ('suffering_death', 'Wahala da Mutuwa'), ('resurrection', 'Tashi daga Matattu'), ('lords_day_after_resurrection', 'Ranar Ubangiji bayan Tashi'), ('ascension', 'Haɗuwa Sama'), ('holy_ghost', 'Ruhu Mai Tsarki'), ('pentecostal_revival', 'Sabuntawa Pentikosti'), ('missionary', 'Ayyukan Mishan'), ('word_of_god', 'Kalmar Allah'), ('baptism', 'Baftisma'), ('holy_communion', 'Tarayyar Mai Tsarki'), ('holy_matrimony', 'Aure Mai Tsarki'), ('children_youth', 'Yara da Matasa'), ('prayer', 'Addu’a'), ('divine_healing', 'Warkarwa daga Allah'), ('faith', 'Bangaskiya'), ('unity_peace', 'Haɗin kai da Salama'), ('time_old_age', 'Lokacin Tsofanci'), ('harvest_anniversaries', 'Girbi da Tunawa'), ('love', 'Soyayya'), ('guidance_protection', 'Jagora da Kariya'), ('labour_service', 'Aiki da Hidima'), ('trials_victories', 'Jarabawa da Nasara'), ('encouragement', 'Karfi da Gwiwa'), ('building_dedication', 'Gina da Kaddamarwa'), ('servants_for_god', 'Bayin Allah'), ('farewell', 'Ban Kwana'), ('church_heaven_earth', 'Ikilisiya a Sama da Duniya'), ('various_hymns', 'Waƙoƙin Daban-daban')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='hymn_images/')),
            ],
        ),
        migrations.CreateModel(
            name='IgboHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hymn_type', models.CharField(choices=[('morning', 'Ụtụtụ'), ('evening', 'Mgbede'), ('the_lords_day', 'Ụbọchị nke Onyenwe anyị'), ('praises', 'Abụ Otuto'), ('advent', 'Mbata Kraịst'), ('christmas', 'Krismas'), ('closing_opening_year', 'Mmechi na Mmeghe Afọ Ọhụrụ'), ('warning_petition_gospel_call', 'Ịdọ Aka ná Ntị, Arịrịọ na Oku Nke Oziọma'), ('lent_repentance', 'Ubochi ịlụnụ Mmehie (Lent) na Nloghachi'), ('palm_sunday', 'Ụka Ụkwụ Ọma (Palm Sunday)'), ('suffering_death', 'Ịrụ Uju na Onwu'), ('resurrection', 'Nbilite n’Ọnwụ'), ('lords_day_after_resurrection', 'Ụbọchị Onyenwe anyị Mgbe Nbilite n’Ọnwụ'), ('ascension', 'Ịrị Eluigwe'), ('holy_ghost', 'Mmụọ Nsọ'), ('pentecostal_revival', 'Mmemme Pentecost'), ('missionary', 'Ozi Kraịst'), ('word_of_god', 'Okwu Chineke'), ('baptism', 'Baptizim'), ('holy_communion', 'Nri Nsọ'), ('holy_matrimony', 'Alụmdi na Nwunye Nsọ'), ('children_youth', 'Ụmụaka na Ụmụaka Ntorobịa'), ('prayer', 'Ekpere'), ('divine_healing', 'Ngọzi Ọgwụsite N’aka Chineke'), ('faith', 'Ok believe (Nkwenye/Okwe Nke Kraịst)'), ('unity_peace', 'Udo na Nzukọ'), ('time_old_age', 'Oge Ọgụgụ Ndụ'), ('harvest_anniversaries', 'Mmepụta na Emume'), ('love', 'Ihụnanya'), ('guidance_protection', 'Ntuziaka na Nchedo'), ('labour_service', 'Ọrụ aka na Ọrụ Nsọ'), ('trials_victories', 'Nnwale na Mmeri'), ('encouragement', 'Nkwalite Obi'), ('building_dedication', 'Inye Ụlọ Nsọ Ọma'), ('servants_for_god', 'Oru Ndị Kraịst'), ('farewell', 'Ịkpọpụ Ọfọ'), ('church_heaven_earth', 'Ụka N’eluigwe na Ụwa'), ('various_hymns', 'Abụ Dị iche iche')], max_length=100)),
                ('image', models.ImageField(upload_to='igbo_hymns/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YorubaHymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hymn_type', models.CharField(choices=[('morning', 'Owuro'), ('evening', 'Irole'), ('the_lords_day', 'Ojo Oluwa'), ('praises', 'Orin Iyin'), ('advent', 'Adifenti'), ('christmas', 'Keresimesi'), ('closing_opening_year', 'Ipade Odun Tuntun'), ('warning_petition_gospel_call', 'Ikilọ, Ibere ati Ipe Ihinrere'), ('lent_repentance', 'Akoko Iwẹ̀wẹ̀ ati Ironupiwada'), ('palm_sunday', 'Ojobo Ọpẹ'), ('suffering_death', 'Irora ati Iku'), ('resurrection', 'Ajinde'), ('lords_day_after_resurrection', 'Ọjọ Oluwa lẹ́yìn Ajinde'), ('ascension', 'Gíga sọdọ Ọlọrun'), ('holy_ghost', 'Ẹmí Mímọ́'), ('pentecostal_revival', 'Ìsọdọtun Pentikọsti'), ('missionary', 'Ìrànṣẹ́ Ọlọ́run'), ('word_of_god', 'Ọ̀rọ̀ Ọlọ́run'), ('baptism', 'Ìbaptisi'), ('holy_communion', 'Ajọpọ Mímọ́'), ('holy_matrimony', 'Ìgbéyàwó Mímọ́'), ('children_youth', 'Ọmọde ati Ọdọ́'), ('prayer', 'Àdúrà'), ('divine_healing', 'Ìwòsàn Ọlọ́run'), ('faith', 'Ìgbàgbọ́'), ('unity_peace', 'Ìṣọ̀kan àti Aláàfíà'), ('time_old_age', 'Àkókò Arugbo'), ('harvest_anniversaries', 'Ikore àti Ayẹyẹ ọdún'), ('love', 'Ìfẹ́'), ('guidance_protection', 'Ìtọ́sọ́nà àti Àbò'), ('labour_service', 'Iṣẹ́ àti Ìránṣẹ́'), ('trials_victories', 'Ìdánwò àti Ìṣegun'), ('encouragement', 'Ìtìlẹ́yìn'), ('building_dedication', 'Ìtajà ati Ìyàsímímọ́'), ('servants_for_god', 'Ìrànṣẹ́ fún Ọlọ́run'), ('farewell', 'Ìkíni Ọ̀fẹ́'), ('church_heaven_earth', 'Ìjọ lórí Ilẹ̀ àti lórí Ọ̀run'), ('various_hymns', 'Orin orisirisi')], max_length=100)),
                ('image', models.ImageField(upload_to='yoruba_hymns/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
