# Generated by Django 4.2.20 on 2025-04-14 20:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_hausahymn_igbohymn_yorubahymn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausahymn',
            name='lyrics',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='igbohymn',
            name='lyrics',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='yorubahymn',
            name='lyrics',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='frenchhymn',
            name='lyrics',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
