# Generated by Django 4.2.20 on 2025-04-16 09:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_hausahymn_lyrics_igbohymn_lyrics_yorubahymn_lyrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='English_Hymn_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
