# Generated by Django 4.2.20 on 2025-04-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_english_hymn_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English_Hymn_Content',
            new_name='Hymn_Content',
        ),
    ]
