# Generated by Django 4.2.20 on 2025-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='We received your message', max_length=255)),
                ('message', models.TextField(default="Hi {name},\n\nThanks for contacting us. We'll get back to you shortly.\n\n- Admin")),
            ],
        ),
    ]
