# Generated by Django 4.2.20 on 2025-04-18 11:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_autoreplymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('history', ckeditor.fields.RichTextField(blank=True)),
                ('the_man', ckeditor.fields.RichTextField(blank=True)),
                ('mission_statement', ckeditor.fields.RichTextField(blank=True)),
                ('vision', ckeditor.fields.RichTextField(blank=True)),
                ('value', ckeditor.fields.RichTextField(blank=True)),
                ('mandate', ckeditor.fields.RichTextField(blank=True)),
                ('contact_address', ckeditor.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
