# Generated by Django 4.2.20 on 2025-04-18 20:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='more_history',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
