# Generated by Django 4.2.20 on 2025-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_aboutpage_more_history_alter_aboutpage_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='coming_soon_backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
