# Generated by Django 4.2.20 on 2025-04-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_comingsoonpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoonpage',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
