# Generated by Django 4.2.20 on 2025-05-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0026_newupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='newupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='new_updates/'),
        ),
    ]
