# Generated by Django 4.2.20 on 2025-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0029_alter_newupdate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='has_closed_modal',
            field=models.BooleanField(default=False),
        ),
    ]
