# Generated by Django 4.2.20 on 2025-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
