# Generated by Django 4.2.20 on 2025-05-25 17:28

import cloudinary.models
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0034_alter_aboutpage_image1_alter_aboutpage_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='comingsoonpage',
            name='background_image',
            field=models.ImageField(upload_to='coming_soon_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='image',
            field=models.ImageField(upload_to='contact_images/'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='frenchhymn',
            name='image',
            field=models.ImageField(upload_to='french_hymns/images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uploaded_file',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='hausahymn',
            name='image',
            field=models.ImageField(blank=True, upload_to='hymn_images/'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='image',
            field=models.ImageField(upload_to='hymns/images/'),
        ),
        migrations.AlterField(
            model_name='igbohymn',
            name='image',
            field=models.ImageField(upload_to='igbo_hymns/'),
        ),
        migrations.AlterField(
            model_name='newupdate',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional – You may leave the image empty.', null=True, upload_to='new_updates/'),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', validators=[files.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='yorubahymn',
            name='image',
            field=models.ImageField(upload_to='yoruba_hymns/'),
        ),
    ]
