# Generated by Django 4.2.20 on 2025-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0036_remove_fileupload_uploaded_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
