# Generated by Django 4.2.20 on 2025-06-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0039_prayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(default='🔥', max_length=5)),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
