# Generated by Django 4.2.20 on 2025-06-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0040_testimony'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
