# Generated by Django 4.2.20 on 2025-07-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0041_delete_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenMinistryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='children/photos/')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Children Ministry Photo',
                'verbose_name_plural': 'Children Ministry Photos',
            },
        ),
        migrations.CreateModel(
            name='EvangelismMinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leaders/evangelism/')),
            ],
            options={
                'verbose_name': 'Evangelism Ministry Leader',
                'verbose_name_plural': 'Evangelism Ministry Leaders',
            },
        ),
        migrations.CreateModel(
            name='MenMinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leaders/men/')),
            ],
            options={
                'verbose_name': 'Men Ministry Leader',
                'verbose_name_plural': 'Men Ministry Leaders',
            },
        ),
        migrations.CreateModel(
            name='WomenMinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leaders/women/')),
            ],
            options={
                'verbose_name': 'Women Ministry Leader',
                'verbose_name_plural': 'Women Ministry Leaders',
            },
        ),
        migrations.CreateModel(
            name='WorshipMinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leaders/worship/')),
            ],
            options={
                'verbose_name': 'Worship Ministry Leader',
                'verbose_name_plural': 'Worship Ministry Leaders',
            },
        ),
        migrations.CreateModel(
            name='YouthMinistryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='leaders/youth/')),
            ],
            options={
                'verbose_name': 'Youth Ministry Leader',
                'verbose_name_plural': 'Youth Ministry Leaders',
            },
        ),
    ]
