# Generated by Django 4.2.20 on 2025-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0042_childrenministryphoto_evangelismministryleader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMSOMSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gmsom/slides/')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'GMSOM Slide Image',
                'verbose_name_plural': 'GMSOM Slide Images',
            },
        ),
    ]
