# Generated by Django 4.2.20 on 2025-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0043_gmsomslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='pdfupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pdfupload',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='image_url',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/337/337946.png', null=True),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='pdf_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
