# Generated by Django 4.2.20 on 2025-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0045_remove_aboutpage_image1_remove_aboutpage_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pinterest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='tumblr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vimeo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
