# Generated by Django 4.2.20 on 2025-07-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0046_aboutpage_facebook_url_aboutpage_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image1_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image3_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='tumblr_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vimeo_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
