# Generated by Django 4.2.20 on 2025-07-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0047_remove_aboutpage_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image3',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image3_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
