# Generated by Django 4.2.20 on 2025-07-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0048_remove_aboutpage_image1_remove_aboutpage_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image2_url',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='image3_url',
        ),
    ]
