# Generated by Django 4.2.20 on 2025-07-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0049_remove_aboutpage_image2_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoonpage',
            name='background_image',
        ),
        migrations.AddField(
            model_name='comingsoonpage',
            name='background_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
