# Generated by Django 4.2.20 on 2025-07-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0050_remove_comingsoonpage_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newupdate',
            name='image',
        ),
        migrations.AddField(
            model_name='newupdate',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional – paste image URL (e.g., Firebase link)', null=True),
        ),
    ]
