# Generated by Django 4.2.20 on 2025-07-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0051_remove_newupdate_image_newupdate_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinesehymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='frenchhymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='germanhymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hausahymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='igbohymn',
            name='image',
        ),
        migrations.RemoveField(
            model_name='yorubahymn',
            name='image',
        ),
    ]
