# Generated by Django 4.2.20 on 2025-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0052_remove_chinesehymn_image_remove_frenchhymn_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
