# Generated by Django 4.2.20 on 2025-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0053_prayerrequest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOfMinistryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state_city', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('church', models.CharField(blank=True, max_length=255)),
                ('born_again', models.CharField(max_length=5)),
                ('holy_ghost', models.CharField(max_length=5)),
                ('reason', models.TextField()),
                ('photo', models.ImageField(upload_to='registrations/photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
