# Generated by Django 4.2.20 on 2025-07-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0054_schoolofministryregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmsomslide',
            name='image',
        ),
        migrations.AddField(
            model_name='gmsomslide',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
