# Generated by Django 4.2.20 on 2025-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0055_remove_gmsomslide_image_gmsomslide_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='born_again',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='church',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='holy_ghost',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolofministryregistration',
            name='state_city',
            field=models.CharField(max_length=50),
        ),
    ]
