# Generated by Django 4.2.20 on 2025-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0056_alter_schoolofministryregistration_born_again_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenMinistryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChildrenMinistryPhoto',
        ),
    ]
