# Generated by Django 4.2.20 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0057_childrenministryregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenministryregistration',
            name='age_group',
            field=models.CharField(choices=[('toddlers', 'Toddlers (0–3 yrs)'), ('preschool', 'Preschool (4–5 yrs)'), ('kids', 'Kids (6–9 yrs)'), ('preteens', 'Pre-teens (10–12 yrs)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='childrenministryregistration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
