# Generated by Django 4.2.20 on 2025-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0058_alter_childrenministryregistration_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('icon', models.CharField(default='fas fa-calendar-alt', help_text="Font Awesome icon class e.g. 'fas fa-fire' or 'fas fa-users'", max_length=50)),
                ('theme_color', models.CharField(default='text-indigo-500', help_text="Tailwind color class for icon e.g. 'text-amber-500', 'text-indigo-500'", max_length=30)),
            ],
            options={
                'verbose_name': 'Youth Event',
                'verbose_name_plural': 'Youth Events',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='YouthMinistryLeader',
        ),
    ]
