# Generated by Django 4.2.20 on 2025-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0059_youthevent_delete_youthministryleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fas fa-star', help_text="Font Awesome icon class e.g. 'fas fa-heart'", max_length=50)),
                ('theme_color', models.CharField(default='text-pink-500', help_text="Tailwind color class for icon e.g. 'text-pink-500'", max_length=30)),
            ],
            options={
                'verbose_name': 'Women Event',
                'verbose_name_plural': 'Women Events',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='WomenMinistryLeader',
        ),
    ]
