# Generated by Django 4.2.20 on 2025-07-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0060_womenevent_delete_womenministryleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fas fa-fire-alt', help_text="Font Awesome icon class e.g. 'fas fa-fire-alt'", max_length=50)),
                ('theme_color', models.CharField(default='text-blue-600', help_text="Tailwind color class e.g. 'text-blue-600'", max_length=30)),
            ],
            options={
                'verbose_name': 'Men Event',
                'verbose_name_plural': 'Men Events',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='MenMinistryLeader',
        ),
    ]
