# Generated by Django 4.2.20 on 2025-07-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0061_menevent_delete_menministryleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fas fa-cross', help_text="Font Awesome icon class e.g. 'fas fa-bullhorn'", max_length=50)),
                ('theme_color', models.CharField(default='text-red-700', help_text="Tailwind color class e.g. 'text-red-600'", max_length=30)),
            ],
            options={
                'verbose_name': 'Outreach Event',
                'verbose_name_plural': 'Outreach Events',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='EvangelismMinistryLeader',
        ),
        migrations.DeleteModel(
            name='WorshipMinistryLeader',
        ),
    ]
